-- Auto-generated from schema-map-postgres.yaml (map@94ebe6c)
-- engine: postgres
-- table:  privacy_requests

CREATE TABLE IF NOT EXISTS privacy_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  "type" TEXT NOT NULL,                         -- 'access','erasure','rectify','restrict','portability'
  status TEXT NOT NULL DEFAULT 'pending',
  requested_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  processed_at TIMESTAMPTZ(6) NULL,
  meta JSONB NULL,
  CONSTRAINT chk_pr_type CHECK ("type" IN ('access','erasure','rectify','restrict','portability')),
  CONSTRAINT chk_pr_status CHECK (status IN ('pending','processing','done','failed','cancelled'))
);
